### ISSUE TITLE
Typo in the theory section of "Solving thermal porous convection"

### ISSUE THREAD

**Issue by youwuyou** [eth-vaw-glaciology/course-101-0250-00#11]
In the following section of lecture 4 we substitute the Fourier heat flux $q_F$ with the coefficient term by the temperature diffusion flux in the equation.

![image](https://user-images.githubusercontent.com/82619264/196040276-43c045c4-4911-42c3-a9fe-437e2fd61684.png)

The typo should be corrected to "instead of using the Fourier heat flux $\vec{q_F}$ " here

**Comment by luraess** [comment]
Thanks!
