### ISSUE TITLE
L6: why show the license?

### ISSUE THREAD

**Issue by mauro3** [eth-vaw-glaciology/course-101-0250-00#13]
In L6 (https://pde-on-gpu.vaw.ethz.ch/lecture6/) this shows:
![image](https://github.com/eth-vaw-glaciology/course-101-0250-00/assets/4098145/31fd8019-20f9-4bbd-8fc3-21f52fb99ea3)

Why mention the license here?  All is covered by MIT/CC BY-SA

**Comment by luraess** [comment]
I know. It was Sam's wish as this notebook was also used in one of his course at CSCS and he wanted to be sure CSCS is mentioned here in online material. From my point, we could strip it...
