### ISSUE TITLE
Bring back computing info on Piz Daint

### ISSUE THREAD

**Issue by youwuyou** [eth-vaw-glaciology/course-101-0250-00#20]
In the "Software Update" section of the website this [particular hyperlink](https://github.com/eth-vaw-glaciology/course-101-0250-00/blob/856960b23fc7dbdc410296223c188297c344887e/website/software_install.md?plain=1#L59) to remote settings is now not pointing to any existing subsections 
![image](https://github.com/user-attachments/assets/778b1efb-721a-48c6-a7ab-d5b0f7e46d01).

It was on the discussion to bring back the setup for Piz Daint to the website, and I see it is essentially the content in this commit [here](https://github.com/eth-vaw-glaciology/course-101-0250-00/commit/caa5249f871781c7be0b3550260529cb444c8590).

Maybe we shall resolve it before the lecture 7 on 29th October?

**Comment by luraess** [comment]
Done in https://github.com/eth-vaw-glaciology/course-101-0250-00/commit/deca7e11a64ee52c5b87d2227b176cb705d21521 @youwuyou
