### ISSUE TITLE
Typo in the description of exercises

### ISSUE THREAD

**Issue by youwuyou** [eth-vaw-glaciology/course-101-0250-00#9]
In the exercise of week 03 "Implicit transient diffusion using dual timestepping", the inner loop for the pseudo-time stepping has a wrong loop-condition.

![image](https://user-images.githubusercontent.com/82619264/194747602-2c5d014c-af78-49d1-8eac-cbf31ed6860f.png)

**Comment by luraess** [comment]
Thanks for spotting this @youwuyou ! Should be fixed now.
